django_tablica/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('tablica.urls')),
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
]

tablica/urls.py
from django.urls import path

from . import views

app_name = 'tablica'
urlpatterns = [
    path('', views.ListaPostow.as_view(), name='post_lista'),
    path('dodaj', views.dodaj_post, name='post_dodaj'),
    path('usun.<int:pk>', views.UsunPost.as_view(), name='post_usun')
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('rejestruj/', views.rejestruj, name='rejestruj'),
    path('loguj/', views.loguj, name='loguj'),
    path('wyloguj/', views.wyloguj, name='wyloguj'),
]

tablica/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Post(models.Model):
    uzytkownik = models.ForeignKey(User, on_delete=models.CASCADE)
    tresc = models.CharField(max_length=1024)
    data_dodania = models.DateField()

    def __str__(self):
        return self.uzytkownik.username + ': ' + self.tresc

users/models.py
# Create your models here.

tablica/forms.py
from django import forms


class PostForm(forms.Form):
    tresc = forms.CharField(
        label="Treść:",
        max_length=1024
    )

users/forms.py
from django import forms


class UserLoginForm(forms.Form):
    login = forms.CharField(
        label="Twój login:",
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    haslo = forms.CharField(
        label="Twoje hasło:",
        max_length=39,
        widget=forms.TextInput(attrs={'class': 'form-control', 'type': 'password'})
    )

tablica/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
# Create your views here.
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.views.generic import ListView, DeleteView

from tablica.forms import PostForm
from tablica.models import Post


@login_required
def dodaj_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            p = Post(tresc=form.cleaned_data['tresc'])
            p.uzytkownik = request.user
            p.data_dodania = timezone.now()
            p.save()
            messages.success(request, "Dodano post!")
            return redirect(reverse("tablica:post_lista"))
    else:
        form = PostForm()
    kontekst = {
        'form': form
    }
    return render(request, 'tablica/post_dodaj.html', kontekst)


class ListaPostow(ListView):
    model = Post
    context_object_name = "posty"
    template_name = "tablica/index.html"
    ordering = ["-data_dodania"]


class UsunPost(SuccessMessageMixin, DeleteView):
    model = Post
    success_url = reverse_lazy("tablica:post_lista")
    success_message = "Usunięto post!"

users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.urls import reverse

from users.forms import UserLoginForm


def wyloguj(request):
    logout(request)
    messages.info(request, "Zostałeś wylogowany!")
    return redirect(reverse('tablica:post_lista'))


def rejestruj(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Konto utworzono!")
            return redirect(reverse("tablica:post_lista"))

    else:
        form = UserCreationForm()

    kontekst = {'form': form}
    return render(request, 'users/rejestruj.html', kontekst)


def loguj(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            nazwa = form.cleaned_data['login']
            haslo = form.cleaned_data['haslo']
            user = authenticate(request, username=nazwa, password=haslo)
            if user is not None:
                login(request, user)
                messages.success(request, "Zostałeś zalogowany")
                return redirect(reverse("tablica:post_lista"))
            else:
                messages.error(request, "Błędny login, lub hasło")

    else:
        form = UserLoginForm()

    kontekst = {'form': form}
    return render(request, 'users/loguj.html', kontekst)

tablica/templates/tablica/index.html
{% extends 'szablon.html' %}
{% block tytul %} Django tablica{% endblock %}
{% block naglowek %}Lista postów{% endblock %}
{% block tresc %}
    <ul class="list-group">
    {% for post in posty %}
        <li class="list-group-item">
            <b>{{ post.tresc }}</b>
            <br>
            {{ post.uzytkownik.username }}
            <br>
            {{ post.data_dodania }}
            {% if user.is_staff %}
                <br>
                <a href="{% url 'tablica:post_usun' post.id %}">
                    <button class="btn btn-danger">Usuń</button>
                </a>
            {% endif %}
        </li>
    {% endfor %}
    </ul>
{% endblock %}

tablica/templates/tablica/post_confirm_delete.html
{% extends 'szablon.html' %}
{% block tytul %}Usun post{% endblock %}
{% block naglowek %}Usuń post{% endblock %}
{% block tresc %}
    <form method="POST">
        {% csrf_token %}
        <p>Usunąć post <strong>{{ object.tresc }}</strong>?</p>
        <button class="btn btn-danger">Usuń</button>
    </form>
{% endblock %}

tablica/templates/tablica/post_dodaj.html
{% extends 'szablon.html' %}
{% block tytul %}Dodaj post{% endblock %}
{% block naglowek %}Utwórz post{% endblock %}
{% block tresc %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Dodaj">
    </form>
{% endblock %}

templates/szablon.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block tytul %}Django tablica{% endblock tytul %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Tablica</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url "tablica:post_lista" %}">Strona główna</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url "tablica:post_dodaj" %}">Dodaj post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "users:wyloguj" %}">Wyloguj się</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url "users:rejestruj" %}">Zarejestruj się</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "users:loguj" %}">Zaloguj się</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
<div class="container">
    <div class="row">
        <div class="col">
            <h1>{% block naglowek %}Aplikacja Django{% endblock naglowek %}</h1>

            {% if messages %}
                {% for komunikat in messages %}
                    <div class="alert alert-success">
                        {{ komunikat }}
                    </div>
                {% endfor %}
            {% endif %}

            {% block tresc %} Aplikacja Django{% endblock tresc %}
        </div>
    </div>
</div>
</body>
</html>

users/templates/users/loguj.html
{% extends 'szablon.html' %}
{% block tytul %}Użytkownicy{% endblock tytul %}
{% block naglowek %}Logowanie{% endblock naglowek %}
{% block tresc %}
    {% if user.is_authenticated %}
        <p>Jesteś już zalogowany jako {{ user.username }}</p>
    {% else %}
        {{ form.errors }}
        <form action="." method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Zaloguj" class="btn waves-effect waves-light btn-primary">
        </form>
    {% endif %}
{% endblock tresc %}

users/templates/users/rejestruj.html
{% extends 'szablon.html' %}
{% block tytul %}Użytkownicy{% endblock tytul %}
{% block naglowek %}Rejestracja{% endblock naglowek %}
{% block tresc %}
    {% if user.is_authenticated %}
        <p>Jesteś już zalogowany jako {{ user.username }}</p>
    {% else %}
        {{ form.errors }}
        <form action="." method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Zapisz" class="btn btn-primary">
        </form>
    {% endif %}
{% endblock tresc %}